//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objectivity.Bot.BaseDialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Objectivity.Bot.BaseDialogs.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, Something went wrong, Ill check that later for sure!.
        /// </summary>
        internal static string CodeError {
            get {
                return ResourceManager.GetString("CodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I don&apos;t know how to do that yet..
        /// </summary>
        internal static string DidNotUnderstand {
            get {
                return ResourceManager.GetString("DidNotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of following intents does not have description : .
        /// </summary>
        internal static string Log_SimillarIntents {
            get {
                return ResourceManager.GetString("Log_SimillarIntents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m confused, what do you want me to do?.
        /// </summary>
        internal static string SimillarIntents {
            get {
                return ResourceManager.GetString("SimillarIntents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a {0}.
        /// </summary>
        internal static string SpecifyParameter {
            get {
                return ResourceManager.GetString("SpecifyParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To find out what I can do simply type &lt;b&gt;help&lt;/b&gt; or read &lt;a href=&quot;{0}&quot;&gt;Lily Guide&lt;/a&gt;.
        /// </summary>
        internal static string TypeHelpOrReadGuide {
            get {
                return ResourceManager.GetString("TypeHelpOrReadGuide", resourceCulture);
            }
        }
    }
}
